#!/usr/bin/env python3
"""Generate Markdown documentation for every function in the project.

Single source of truth: docstrings (Python) and leading comment blocks
(JSDoc-style or plain `//` runs) for JS/JSX. Mirrors the source tree
into `docs/`. Runs in two modes:

  python scripts/generate_docs.py            # regenerate docs/
  python scripts/generate_docs.py --check    # exit 1 if docs drift

The check mode is what the pre-commit hook calls — when a function's
signature/docstring changes but the contributor forgot to regenerate
the .md, the commit is blocked with a clear message.

Design notes:
- Python uses `ast` (real parser, never wrong on syntax).
- JS uses a comment-aware regex pass over the source. Covers the
  patterns this repo uses: `export function foo(...)`,
  `function foo(...)`, `const foo = (...) =>`, `export const foo =`.
  Not a full JS parser — that's the deliberate trade for zero deps.
- We intentionally document EVERY function, not just public ones, so
  readers can trace internals. Private (_-prefixed) functions get a
  small "Internal" marker so the public surface stays scannable.
- Generated files carry a `<!-- AUTOGENERATED -->` header. If a human
  edits a generated file by hand, the next `--check` run will see the
  drift and report it — that's a feature, not a bug.

The script is intentionally dependency-free (stdlib only) so it runs
on any host with Python 3.9+ and never requires `pip install`.
"""
from __future__ import annotations

import argparse
import ast
import os
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable

REPO_ROOT = Path(__file__).resolve().parent.parent
DOCS_DIR = REPO_ROOT / "docs"

# Folders whose code we DOCUMENT. Anything not in this list is ignored
# so vendored / generated / fixture trees don't pollute /docs.
SOURCE_ROOTS = [
    REPO_ROOT / "legal_app" / "backend",
    REPO_ROOT / "src",
    REPO_ROOT / "scripts",
]

# Files in those roots we explicitly skip.
IGNORE_PATTERNS = {
    "node_modules", "__pycache__", ".pytest_cache",
    "dist", "build", ".venv", "venv",
    # Test files: keep but mark them as test files (less detail).
}

PY_EXTS = {".py"}
JS_EXTS = {".js", ".jsx"}

HEADER = (
    "<!-- AUTOGENERATED by scripts/generate_docs.py — do not edit by hand. -->\n"
    "<!-- Re-run `npm run docs` (or `python scripts/generate_docs.py`) after\n"
    "     changing the function it describes. The pre-commit hook will block\n"
    "     a commit that changes a function without regenerating its doc. -->\n\n"
)


# ---------------------------------------------------------------------------
# data shape
# ---------------------------------------------------------------------------

@dataclass
class FunctionDoc:
    name: str
    kind: str  # "function" | "method" | "class" | "constant"
    signature: str
    docstring: str
    is_private: bool
    line: int
    is_async: bool = False
    decorators: list[str] = field(default_factory=list)


@dataclass
class ModuleDoc:
    rel_path: Path  # relative to repo root (e.g. legal_app/backend/main.py)
    language: str   # "python" | "javascript"
    module_doc: str
    functions: list[FunctionDoc] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Python extraction
# ---------------------------------------------------------------------------

def _format_py_arg(arg: ast.arg, default: ast.expr | None) -> str:
    name = arg.arg
    annotation = ""
    if arg.annotation is not None:
        try:
            annotation = ": " + ast.unparse(arg.annotation)
        except Exception:
            annotation = ""
    default_str = ""
    if default is not None:
        try:
            default_str = " = " + ast.unparse(default)
        except Exception:
            default_str = " = ..."
    return name + annotation + default_str


def _format_py_signature(node: ast.FunctionDef | ast.AsyncFunctionDef) -> str:
    a = node.args
    parts: list[str] = []
    # positional-only
    positional = a.posonlyargs + a.args
    defaults = list(a.defaults)
    # pad defaults to align with the right end of positionals
    pad = len(positional) - len(defaults)
    aligned = [None] * pad + defaults
    for arg, default in zip(positional, aligned):
        parts.append(_format_py_arg(arg, default))
    if a.posonlyargs:
        # insert "/" after the last positional-only
        parts.insert(len(a.posonlyargs), "/")
    if a.vararg:
        parts.append("*" + _format_py_arg(a.vararg, None))
    elif a.kwonlyargs:
        parts.append("*")
    for arg, default in zip(a.kwonlyargs, a.kw_defaults):
        parts.append(_format_py_arg(arg, default))
    if a.kwarg:
        parts.append("**" + _format_py_arg(a.kwarg, None))
    returns = ""
    if node.returns is not None:
        try:
            returns = " -> " + ast.unparse(node.returns)
        except Exception:
            returns = ""
    return f"{node.name}({', '.join(parts)}){returns}"


def _py_decorator_list(node) -> list[str]:
    out = []
    for d in getattr(node, "decorator_list", []):
        try:
            out.append("@" + ast.unparse(d))
        except Exception:
            pass
    return out


def extract_python(path: Path) -> ModuleDoc:
    src = path.read_text(encoding="utf-8")
    try:
        tree = ast.parse(src)
    except SyntaxError as e:
        return ModuleDoc(
            rel_path=path.relative_to(REPO_ROOT),
            language="python",
            module_doc=f"_Could not parse: {e}_",
        )
    module_doc = ast.get_docstring(tree) or ""
    funcs: list[FunctionDoc] = []
    # Walk top-level + class methods one nesting deep — recursive walking
    # adds noise (nested helpers inside functions) we don't need.
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            funcs.append(FunctionDoc(
                name=node.name,
                kind="function",
                signature=_format_py_signature(node),
                docstring=ast.get_docstring(node) or "",
                is_private=node.name.startswith("_") and not node.name.startswith("__"),
                line=node.lineno,
                is_async=isinstance(node, ast.AsyncFunctionDef),
                decorators=_py_decorator_list(node),
            ))
        elif isinstance(node, ast.ClassDef):
            funcs.append(FunctionDoc(
                name=node.name,
                kind="class",
                signature=f"class {node.name}",
                docstring=ast.get_docstring(node) or "",
                is_private=node.name.startswith("_"),
                line=node.lineno,
                decorators=_py_decorator_list(node),
            ))
            for child in node.body:
                if isinstance(child, (ast.FunctionDef, ast.AsyncFunctionDef)):
                    funcs.append(FunctionDoc(
                        name=f"{node.name}.{child.name}",
                        kind="method",
                        signature=_format_py_signature(child),
                        docstring=ast.get_docstring(child) or "",
                        is_private=child.name.startswith("_") and not child.name.startswith("__"),
                        line=child.lineno,
                        is_async=isinstance(child, ast.AsyncFunctionDef),
                        decorators=_py_decorator_list(child),
                    ))
    return ModuleDoc(
        rel_path=path.relative_to(REPO_ROOT),
        language="python",
        module_doc=module_doc,
        functions=funcs,
    )


# ---------------------------------------------------------------------------
# JS / JSX extraction
# ---------------------------------------------------------------------------

# Matches:
#   export function foo(args) {
#   export async function foo(args) {
#   export default function foo(args) {
#   function foo(args) {
#   export const foo = (args) =>
#   export const foo = function (args) {
#   const foo = (args) =>
#   export class Foo {
JS_FN_RE = re.compile(
    r"^(?P<indent>[ \t]*)"
    r"(?P<exported>export\s+(?:default\s+)?)?"
    r"(?:"
    r"(?P<async1>async\s+)?function\s+(?P<name1>[A-Za-z_$][\w$]*)\s*\((?P<args1>[^)]*)\)"
    r"|"
    r"(?:const|let|var)\s+(?P<name2>[A-Za-z_$][\w$]*)\s*=\s*(?P<async2>async\s+)?\((?P<args2>[^)]*)\)\s*=>"
    r"|"
    r"(?:const|let|var)\s+(?P<name3>[A-Za-z_$][\w$]*)\s*=\s*(?P<async3>async\s+)?function\s*\((?P<args3>[^)]*)\)"
    r"|"
    r"class\s+(?P<name4>[A-Za-z_$][\w$]*)"
    r")",
    re.MULTILINE,
)


def _strip_comment_marker(line: str) -> str:
    """Strip JSDoc / line-comment markers from a doc line."""
    s = line.strip()
    if s.startswith("/**") or s.startswith("/*"):
        s = s[3:] if s.startswith("/**") else s[2:]
    if s.endswith("*/"):
        s = s[:-2]
    s = s.strip()
    if s.startswith("*"):
        s = s[1:].lstrip()
    elif s.startswith("//"):
        s = s[2:].lstrip()
    return s


def _collect_preceding_comment(lines: list[str], def_line_idx: int) -> str:
    """Look upward from `def_line_idx` for a JSDoc block (`/** ... */`)
    or a contiguous run of `//` lines, blank-line-terminated. Returns
    the cleaned multi-line string (one entry per source line)."""
    i = def_line_idx - 1
    # skip blanks immediately above the def
    while i >= 0 and not lines[i].strip():
        i -= 1
    if i < 0:
        return ""
    # Case A: closing of a JSDoc block
    end = lines[i].strip()
    if end.endswith("*/"):
        block: list[str] = []
        # collect upward until we find /** opener
        while i >= 0:
            block.append(lines[i])
            if lines[i].strip().startswith("/*"):
                break
            i -= 1
        block.reverse()
        return "\n".join(_strip_comment_marker(b) for b in block).strip()
    # Case B: line comments (//) run
    if end.startswith("//"):
        block = []
        while i >= 0 and lines[i].strip().startswith("//"):
            block.append(lines[i])
            i -= 1
        block.reverse()
        return "\n".join(_strip_comment_marker(b) for b in block).strip()
    return ""


def _collect_leading_module_doc(text: str) -> str:
    """The top-of-file banner comment (the one this repo uses everywhere)
    becomes the module docstring."""
    lines = text.splitlines()
    # skip blank lines
    i = 0
    while i < len(lines) and not lines[i].strip():
        i += 1
    if i >= len(lines):
        return ""
    if lines[i].lstrip().startswith("/*"):
        # block comment from i to first */
        block = []
        while i < len(lines):
            block.append(lines[i])
            if lines[i].strip().endswith("*/"):
                break
            i += 1
        return "\n".join(_strip_comment_marker(b) for b in block).strip()
    if lines[i].lstrip().startswith("//"):
        block = []
        while i < len(lines) and lines[i].lstrip().startswith("//"):
            block.append(lines[i])
            i += 1
        return "\n".join(_strip_comment_marker(b) for b in block).strip()
    return ""


def extract_js(path: Path) -> ModuleDoc:
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines()
    module_doc = _collect_leading_module_doc(text)
    funcs: list[FunctionDoc] = []
    for m in JS_FN_RE.finditer(text):
        name = (m.group("name1") or m.group("name2")
                or m.group("name3") or m.group("name4"))
        if not name:
            continue
        is_class = bool(m.group("name4"))
        if is_class:
            args = ""
            signature = f"class {name}"
            kind = "class"
        else:
            args = (m.group("args1") or m.group("args2")
                    or m.group("args3") or "").strip()
            signature = f"{name}({args})"
            kind = "function"
        is_async = bool(m.group("async1") or m.group("async2") or m.group("async3"))
        is_exported = bool(m.group("exported"))
        # Find line number of the match start.
        start_idx = m.start()
        line_no = text.count("\n", 0, start_idx) + 1
        doc = _collect_preceding_comment(lines, line_no - 1)
        # `_`-prefix convention for private. Also non-exported functions
        # that don't start a capital letter are likely internal helpers.
        is_private = name.startswith("_") or (not is_exported and not name[0].isupper() and not _looks_public(name))
        funcs.append(FunctionDoc(
            name=name,
            kind=kind,
            signature=("export " if is_exported else "") + ("async " if is_async else "") + signature,
            docstring=doc,
            is_private=is_private,
            line=line_no,
            is_async=is_async,
        ))
    return ModuleDoc(
        rel_path=path.relative_to(REPO_ROOT),
        language="javascript",
        module_doc=module_doc,
        functions=funcs,
    )


def _looks_public(name: str) -> bool:
    """Identifiers we always treat as public (React/JS conventions)."""
    return name in {"default", "App"} or name.startswith("use")


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------

def _format_docstring(doc: str) -> str:
    if not doc:
        return "_No description provided._"
    # Trim Python-style indent that ast preserves.
    return doc.strip()


def render_module_md(mod: ModuleDoc) -> str:
    out: list[str] = []
    out.append(HEADER.rstrip() + "\n")
    out.append(f"# `{mod.rel_path.as_posix()}`\n")
    out.append(f"_{mod.language.title()} module_\n")
    if mod.module_doc:
        out.append("## Overview\n")
        out.append(mod.module_doc.strip() + "\n")
    public = [f for f in mod.functions if not f.is_private]
    private = [f for f in mod.functions if f.is_private]
    if not mod.functions:
        out.append("_No functions defined at the top level._\n")
        return "\n".join(out)
    if public:
        out.append("## Public API\n")
        for fn in public:
            out.append(_render_function(fn))
    if private:
        out.append("## Internal\n")
        out.append("_Helpers used inside this module. Document them so a "
                   "later refactor doesn't lose the why._\n")
        for fn in private:
            out.append(_render_function(fn))
    return "\n".join(out)


def _render_function(fn: FunctionDoc) -> str:
    lines = []
    badge = ""
    if fn.kind == "class":
        badge = " · class"
    elif fn.kind == "method":
        badge = " · method"
    elif fn.is_async:
        badge = " · async"
    lines.append(f"### `{fn.name}`{badge}\n")
    if fn.decorators:
        lines.append("```\n" + "\n".join(fn.decorators) + "\n```\n")
    lines.append("```\n" + fn.signature + "\n```\n")
    lines.append(_format_docstring(fn.docstring) + "\n")
    lines.append(f"_Defined at line {fn.line}._\n")
    return "\n".join(lines)


def render_folder_readme(folder: Path, modules: list[ModuleDoc], children: list[Path]) -> str:
    rel = folder.relative_to(REPO_ROOT)
    out: list[str] = []
    out.append(HEADER.rstrip() + "\n")
    out.append(f"# `{rel.as_posix()}`\n")
    out.append(f"This folder documents the source tree at `{rel.as_posix()}/`.\n")
    if children:
        out.append("## Sub-folders\n")
        for child in sorted(children):
            child_rel = child.relative_to(folder)
            out.append(f"- [`{child_rel.as_posix()}/`]({child_rel.as_posix()}/README.md)")
        out.append("")
    if modules:
        out.append("## Modules\n")
        for mod in sorted(modules, key=lambda m: m.rel_path.as_posix()):
            file_name = mod.rel_path.name
            md_name = file_name + ".md"
            count = len([f for f in mod.functions if not f.is_private])
            internal = len([f for f in mod.functions if f.is_private])
            summary = (mod.module_doc.split("\n", 1)[0].strip()
                       if mod.module_doc else "_No overview._")
            out.append(f"- [`{file_name}`]({md_name}) — {count} public"
                       + (f", {internal} internal" if internal else "")
                       + f". {summary}")
        out.append("")
    return "\n".join(out)


def render_root_readme(all_modules: list[ModuleDoc]) -> str:
    out: list[str] = []
    out.append(HEADER.rstrip() + "\n")
    out.append("# AG Lex — function reference\n")
    out.append(
        "Auto-generated documentation for every function and class in the\n"
        "project. The folder tree below mirrors the source tree.\n"
    )
    out.append("## How this works\n")
    out.append(
        "- One markdown file per source module, in a folder structure that\n"
        "  mirrors the source tree.\n"
        "- Each function block shows its signature, the docstring/leading\n"
        "  comment from the code, and the line where it lives.\n"
        "- A pre-commit hook (see `tools/hooks/pre-commit`) runs\n"
        "  `python scripts/generate_docs.py --check` and blocks commits\n"
        "  whose code/doc are out of sync. Regenerate locally with:\n\n"
        "  ```\n  npm run docs\n  ```\n"
        "- Bug history lives in [BUGS.md](BUGS.md) and is append-only —\n"
        "  every fixed bug stays in the log forever so we can trace\n"
        "  how each function evolved.\n"
    )
    out.append("## Top-level folders\n")
    roots: dict[str, list[ModuleDoc]] = {}
    for m in all_modules:
        top = m.rel_path.parts[0]
        roots.setdefault(top, []).append(m)
    for top in sorted(roots):
        n = len(roots[top])
        out.append(f"- [`{top}/`]({top}/README.md) — {n} modules")
    out.append("\nFull module index:\n")
    for mod in sorted(all_modules, key=lambda m: m.rel_path.as_posix()):
        public_count = len([f for f in mod.functions if not f.is_private])
        md_rel = mod.rel_path.as_posix() + ".md"
        out.append(f"- [`{mod.rel_path.as_posix()}`]({md_rel}) — {public_count} public")
    return "\n".join(out) + "\n"


# ---------------------------------------------------------------------------
# Walking + IO
# ---------------------------------------------------------------------------

def iter_source_files() -> Iterable[Path]:
    for root in SOURCE_ROOTS:
        if not root.is_dir():
            continue
        for path in root.rglob("*"):
            if any(part in IGNORE_PATTERNS for part in path.parts):
                continue
            if path.is_file() and path.suffix in (PY_EXTS | JS_EXTS):
                yield path


def build_all_modules() -> list[ModuleDoc]:
    mods: list[ModuleDoc] = []
    for path in iter_source_files():
        try:
            if path.suffix in PY_EXTS:
                mods.append(extract_python(path))
            elif path.suffix in JS_EXTS:
                mods.append(extract_js(path))
        except Exception as e:
            # A single broken file should not kill the whole run.
            print(f"[WARN] skipping {path}: {e}", file=sys.stderr)
    return mods


def generate(write: bool = True) -> dict[Path, str]:
    """Returns a {abs_path: content} map of every file the generator
    would write. When `write` is True, also writes them to disk."""
    modules = build_all_modules()
    files: dict[Path, str] = {}

    # Per-module .md
    for mod in modules:
        out_path = DOCS_DIR / mod.rel_path.parent / (mod.rel_path.name + ".md")
        files[out_path] = render_module_md(mod)

    # Per-folder README.md
    folders: dict[Path, list[ModuleDoc]] = {}
    for mod in modules:
        folders.setdefault(DOCS_DIR / mod.rel_path.parent, []).append(mod)

    all_folders = set(folders.keys())
    # add every parent folder up to DOCS_DIR
    for f in list(folders.keys()):
        cur = f
        while cur != DOCS_DIR and cur.parent != cur:
            cur = cur.parent
            all_folders.add(cur)

    for folder in all_folders:
        mods_here = folders.get(folder, [])
        children = [c for c in all_folders if c.parent == folder]
        if folder == DOCS_DIR:
            files[folder / "README.md"] = render_root_readme(modules)
        else:
            files[folder / "README.md"] = render_folder_readme(folder, mods_here, children)

    if write:
        _write_all(files)
    return files


def _write_all(files: dict[Path, str]) -> None:
    # Wipe stale .md generated earlier so removed source files don't
    # leave orphan docs behind. We only touch the per-source mirror
    # under docs/legal_app and docs/src and docs/scripts; everything
    # else (BUGS.md, top-level README's manually-curated extras) is
    # preserved.
    for top in SOURCE_ROOTS:
        try:
            rel = top.relative_to(REPO_ROOT)
        except ValueError:
            continue
        mirror = DOCS_DIR / rel
        if mirror.exists():
            _wipe_generated(mirror, keep=set(files.keys()))

    for path, content in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        existing = path.read_text(encoding="utf-8") if path.exists() else None
        if existing != content:
            path.write_text(content, encoding="utf-8")


def _wipe_generated(folder: Path, keep: set[Path]) -> None:
    for path in folder.rglob("*.md"):
        if path not in keep:
            try:
                path.unlink()
            except OSError:
                pass
    # Don't remove empty dirs — git ignores them anyway and they're
    # harmless.


def check_synced() -> int:
    """Generate in memory and compare to disk. Returns 0 if synced, 1
    if there's drift (with a friendly diff summary)."""
    expected = generate(write=False)
    drift: list[str] = []
    for path, content in expected.items():
        actual = path.read_text(encoding="utf-8") if path.exists() else None
        if actual is None:
            drift.append(f"  MISSING: {path.relative_to(REPO_ROOT).as_posix()}")
        elif actual != content:
            drift.append(f"  STALE:   {path.relative_to(REPO_ROOT).as_posix()}")
    # Detect orphan .md (file in docs/ that the generator wouldn't produce)
    for top in SOURCE_ROOTS:
        try:
            rel = top.relative_to(REPO_ROOT)
        except ValueError:
            continue
        mirror = DOCS_DIR / rel
        if not mirror.exists():
            continue
        for p in mirror.rglob("*.md"):
            if p not in expected:
                drift.append(f"  ORPHAN:  {p.relative_to(REPO_ROOT).as_posix()}")
    if not drift:
        print("docs are in sync with code.")
        return 0
    print("docs are OUT OF SYNC with code:")
    for line in drift:
        print(line)
    print()
    print("Run `npm run docs` (or `python scripts/generate_docs.py`) and stage the changes.")
    return 1


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--check", action="store_true",
                   help="Exit 1 if docs/ doesn't match what would be generated. "
                        "Used by the pre-commit hook.")
    args = p.parse_args()
    if args.check:
        return check_synced()
    generate(write=True)
    print(f"docs written under {DOCS_DIR.relative_to(REPO_ROOT)}/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
